### ISSUE TITLE
Tutorial for building tensorflow  for aarch64

### ISSUE THREAD

**Issue by sanjaybharadwaj** [peterlee0127/tensorflow-nvJetson#12]
Hi Peter,

I appreciate that you are saving the wheels of tensorflow for aarch64 architecture. I am trying to build the same but for Python3. Could you please post me the instructions to build the tensorflow (Patches needed for Basel and other packages for the building).

I currently use Nvidia DrivePX2 as my target.

Thank you and best regards,
Sanjay

**Comment by peterlee0127** [comment]
With Tensorflow 1.5 and later, you can build with this guide. No need any modify anymore. 
Required JetPack 3.2
https://www.tensorflow.org/install/install_sources

**Comment by peterlee0127** [comment]
Yes.
