### ISSUE TITLE
Building script available?

### ISSUE THREAD

**Issue by alejandroandreu** [peterlee0127/tensorflow-nvJetson#13]
Hi,

First off, thanks for your work! It's been of tremendous help to me :+1: I was wondering if you had the scripts that you use to build this? I'd like to do nightly builds on my CI system, and I can't afford for the TX2 to take hours every time...

Cheers!

**Comment by peterlee0127** [comment]
Hi, you can follow the official docs.
https://www.tensorflow.org/install/install_sources

**Comment by alejandroandreu** [comment]
Oh, so you don't do cross-compiling but build them directly on the TX2 board?

**Comment by peterlee0127** [comment]
Yes, I build tensorflow binary directly.

**Comment by alejandroandreu** [comment]
Ok, thanks for your input!
