### ISSUE TITLE
Publish whole binaries

### ISSUE THREAD

**Issue by alejandroandreu** [peterlee0127/tensorflow-nvJetson#17]
Hi!

Just a suggestion :smile: Why don't you publish the whole whl binaries as a whole file? I know that GitHub won't allow you to do that in the Git repo itself, however it is possible if you create releases of the repository.

Thanks again for your work!

**Comment by peterlee0127** [comment]
Hi, Because GitHub repo can only put 100MB of files. And using Git LFS only have 1GB Bandwidth per month.
But I added install script.

```sh -c "$(curl -fsSL https://tfjetson.peterlee0127.com/installTF.sh)"```

**Comment by alejandroandreu** [comment]
Yeah, I know! But I was referring to the "Releases" tab of every repo, like in here: https://github.com/midokura/cuda/releases

I've published one of your binaries as a release because I needed it (so I can `wget` it). I mean it's awesome that you publish the file splitted in two parts, although if you wanted to serve them already as a whole you could do it ;) Cheers!

**Comment by peterlee0127** [comment]
ok. I got it. Thanks
