### ISSUE TITLE
"Architecture is not a supported one" - but it is...

### ISSUE THREAD

**Issue by MikeWise2718** [peterlee0127/tensorflow-nvJetson#18]
Kind of weird, and probably not the fault of the build, but if you have an idea here please let me know. I wrote it up on StackOverflow: [https://stackoverflow.com/questions/50506088/tensorflow-whl-is-not-a-supported-wheel-on-this-platform-although-pep425-tags](https://stackoverflow.com/questions/50506088/tensorflow-whl-is-not-a-supported-wheel-on-this-platform-although-pep425-tags)

**Comment by peterlee0127** [comment]
You may try to install pip 
https://pip.pypa.io/en/stable/installing/
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ sudo python get.pip.py

and check your python is 2.7
$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by MikeWise2718** [comment]
And thank you for the suggestion, it worked. Kind of weird because I had just upgraded to pip 10 which I think is what broke it, but there must have been something wrong with that upgrade.

If you want to answer the SO question, do so and I will mark it right.
