### ISSUE TITLE
Building Tensorflow from source on TX2 without CUDA

### ISSUE THREAD

**Issue by srivatsankrishnan** [peterlee0127/tensorflow-nvJetson#22]
Hi,
I am using your script to build TF from source. During the config step, I entered "N" for "Do you wish to build TensorFlow with CUDA support". The reason why I chose this option is that I want to use CPU version of Tensorflow on TX2. 

This is the error i get when i give that option in my configure step:
_ERROR: /home/nvidia/.cache/bazel/_bazel_nvidia/328b7684270f6fe173a4d80bc65bde15/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/nvidia/.cache/bazel/_bazel_nvidia/328b7684270f6fe173a4d80bc65bde15/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/nvidia/.cache/bazel/_bazel_nvidia/328b7684270f6fe173a4d80bc65bde15/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled_

Have you tried building TF CPU-only version in TX2? Let me know!

Thanks
Sri

**Comment by alejandroandreu** [comment]
https://github.com/peterlee0127/tensorflow-nvJetson/blob/master/buildTensorflow.sh#L11

You should remove `--config=cuda` out of that shell script.
