### ISSUE TITLE
Process for building from source

### ISSUE THREAD

**Issue by sidharthramesh98** [peterlee0127/tensorflow-nvJetson#23]
Hey, I've been trying to build tensorflow from source for a few days. I keep getting a lot of errors of files not being found or created. I'm trying to build on a Jetson TX2 with python 3.5. Can you tell me how you went about it.

Thanks for the help!

**Comment by peterlee0127** [comment]
Hi, you can use virtualenv to switch to python3 to build.

https://docs.python.org/3/library/venv.html
