### ISSUE TITLE
tensorflow-1.9.0 中 protobuf 版本问题

### ISSUE THREAD

**Issue by haiyang-tju** [peterlee0127/tensorflow-nvJetson#24]
请问一下，你在编译 tensorflow-1.9.0-cp35-cp35m-linux_aarch64.whl 时的 protobuf 版本是多少？我在安装过程中默认安装的版本是protobuf 3.6.0，但是在运行TF的时候给出以下错误：

[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/arm-opt/genfiles/tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/arm-opt/genfiles/tensorflow/contrib/tpu/proto/tpu_embedding_config.pb.cc".)

尝试过卸载重装
pip3 uninstall protobuf
pip3 install protobuf
pip3 install protobuf==2.6.1
pip3 install protobuf==3.5.0.post1

均无效，还是有此错误提示。

**Comment by peterlee0127** [comment]
HI, I use the virtualenvs with python 3.5.
protobuf  version is 3.5.2.post1.
You can try to use virtualenvs to setup the build environment.

**Comment by haiyang-tju** [comment]
I am trying to compile Tensorflow with RT myself. 

Is there any special configuration for TensorRT? 
Or just an item in bazel's configure:
    TensorRT support?[y/N]: y

But I am a little confused about that the Tensorflow with RT used an integrated part or an additional installation of TensorRT?

**Comment by peterlee0127** [comment]
Hi, TensorRT is already integrated in JetPack. No need to install tensorRT. Just use the default value.

**Comment by haiyang-tju** [comment]
Thanks for your reply. I will try it.
