### ISSUE TITLE
1.13 and 2.0?

### ISSUE THREAD

**Issue by innerop** [peterlee0127/tensorflow-nvJetson#28]
Thank you for creating this resource.

Any chance we'll see 1.13 and 2.0?

Cheers,

**Comment by peterlee0127** [comment]
Thanks for your comment. 
I may try TensorFlow 2.0.

**Comment by innerop** [comment]
Thank you for that. It will help everyone using the Jetson TX2. NVIDIA's official wheel is 1.9, not sure why since you already have figured out the patch for 1.12 (I got that built just fine on my TX2)
