### ISSUE TITLE
CUDA 9.2

### ISSUE THREAD

**Issue by SeongHyunBae** [peterlee0127/tensorflow-nvJetson#30]
I had a hard time to install tensorflow on drive px2.
Drive px2 has CUDA 9.2 and cudnn 7.2.1.
please help.......
Nvidia just said  refer to here

**Comment by peterlee0127** [comment]
Hi, you can try the build script. 
And [release wheel](https://github.com/peterlee0127/tensorflow-nvJetson/releases) (Jetpack 3.3, CUDA 9)
I only have TX2. I am not sure px2 will work with my build.

**Comment by SeongHyunBae** [comment]
Ok.! thank you!! :)
